#!/bin/bash -e
# Generates a valid PHP script with page content
# Michael Pozhidaev <michael.pozhidaev@gmail.com>
# Date: 2015-11-16

# Usage: lwr-mk-page TARGETDIR INPUTFILE
# TARGETDIR must be without the trailing slash!

THIS="${0##*/}"
TMP_DIR="$(mktemp -d)"
TARGETDIR="$1"
INPUTFILE="$2"

exit_handler()
{
    local rc=$?
    trap - EXIT
    cd 
    /bin/rm -rf -- "$TMP_DIR"
    exit $rc
}

trap exit_handler EXIT HUP INT QUIT PIPE TERM

[ -z "$TARGETDIR" ] && echo "$THIS:no target directory mentioned" >&2 && exit 1 
[ -z "$INPUTFILE" ] && echo "$THIS:no input file mentioned" >&2 && exit 1 

FILE_TYPE="${INPUTFILE##*.}"

ENPAGE="$TMP_DIR/en.licrict"
RUPAGE="$TMP_DIR/ru.licrict"
HEADERFILE="$TMP_DIR/header.sh"
SED_FILE="$TMP_DIR/split.sed"

cat <<EOF > "$SED_FILE"
1,/luwrain-page-en/{
  h
  s/luwrain-page-.*\$//
  w $HEADERFILE
  g
}

/luwrain-page-ru/,\${
  h
  s/luwrain-page-.*\$//
  w $RUPAGE
  g
}

/luwrain-page-en/,/luwrain-page-ru/{
  h
  s/luwrain-page-.*\$//
  w $ENPAGE
  g
}
EOF

sed -n -f "$SED_FILE" "$INPUTFILE"

source "$HEADERFILE"

[ -z "$ENTITLE" ] && echo "$THIS:\$ENTITLE is not set" &>2 && exit 1
[ -z "$RUTITLE" ] && echo "$THIS:\$RUTITLE is not set" &>2 && exit 1
[ -z "$TARGET" ] && echo "$THIS:\$TARGET is not set" &>2 && exit 1

OUTPUTFILE="$TARGETDIR/$TARGET"
INCLUDE="$(echo "$TARGET" | sed s/'[^/]'//g | sed s:/:../:g)functions.php"

(
cat <<EOF
<?php include "$INCLUDE"; luwrain_begin_page('/$TARGET', luwrain_current_lang() == 'ru'?'$RUTITLE':'$ENTITLE');?>
<?php if (luwrain_current_lang() == 'en') {?>
EOF
if [ -r "$ENPAGE" ]; then
    ./lwr-mk-html "$FILE_TYPE" "$ENPAGE"
fi
cat <<EOF
<?php }?>
<?php if (luwrain_current_lang() == 'ru') {?>
EOF
if [ -r "$RUPAGE" ]; then
    ./lwr-mk-html "$FILE_TYPE" "$RUPAGE"
fi
cat <<EOF
<?php }?>
<?php luwrain_end_page('/$TARGET');?>
EOF
) > "$OUTPUTFILE"

echo "$OUTPUTFILE"
