#!/bin/bash -e

TARGETDIR=../files
TEXTSDIR=../texts

while read l; do
    if [ -n "$l" ]; then
	FILE="$(./lws-mk-page "$TARGETDIR" "$TEXTSDIR/$l")"
	./lws-subst "$FILE"
	echo Wrote "$FILE"
    fi
done < "$TEXTSDIR/list.txt"
