#!/bin/bash -e

. config.sh

find "$TEXTSDIR" -iname '*.md' | while read l; do
    FILE="$(./lwr-mk-page "$TARGETDIR" "$l")"
    ./lwr-subst "$FILE"
    echo Wrote "$FILE"
done

find "$TARGETDIR" -type d -exec chmod 755 '{}' \;
find "$TARGETDIR" -type f -exec chmod 644 '{}' \;
