#!/bin/sh -e
# Generates a valid PHP script with page content
# Michael Pozhidaev <michael.pozhidaev@gmail.com>
# Date: 2015-11-16

# Usage: lws-mk-page TARGETDIR INPUTFILE
# TARGETDIR must be without the trailing slash!

THIS="${0##*/}"
INDENT=16
TMP_DIR="$(mktemp -d)"
TARGETDIR="$1"
INPUTFILE="$2"

exit_handler()
{
    local rc=$?
    trap - EXIT
    cd 
    /bin/rm -rf -- "$TMP_DIR"
    exit $rc
}

trap exit_handler EXIT HUP INT QUIT PIPE TERM

[ -z "$TARGETDIR" ] && echo "$THIS:no target directory mentioned" >&2 && exit 1 
[ -z "$INPUTFILE" ] && echo "$THIS:no input file mentioned" >&2 && exit 1 

FILE_TYPE="${INPUTFILE##*.}"

ENPAGE="$TMP_DIR/en.licrict"
RUPAGE="$TMP_DIR/ru.licrict"
HEADERFILE="$TMP_DIR/header.sh"

MODE=header

while read l; do
    if echo "$l" | grep -qi luwrain-page-en; then
	MODE=enpage
    elif echo "$l" | grep -qi luwrain-page-ru; then
	MODE=rupage
    elif [ "$MODE" == enpage ]; then
	echo "$l" >> "$ENPAGE"
    elif [ "$MODE" == rupage ]; then
	echo "$l" >> "$RUPAGE"
    else
	echo "$l" >> "$HEADERFILE"
    fi
done < "$INPUTFILE"

source "$HEADERFILE"

[ -z "$ENTITLE" ] && echo "$THIS:\$ENTITLE is not set" &>2 && exit 1
[ -z "$RUTITLE" ] && echo "$THIS:\$RUTITLE is not set" &>2 && exit 1
[ -z "$TARGET" ] && echo "$THIS:\$TARGET is not set" &>2 && exit 1

OUTPUTFILE="$TARGETDIR/$TARGET"
INCLUDE="$(echo "$TARGET" | sed s/'[^/]'//g | sed s:/:../:g)functions.php"

(
cat <<EOF
<?php include "$INCLUDE"; luwrain_begin_page('/$TARGET', luwrain_current_lang() == 'ru'?'$RUTITLE':'$ENTITLE');?>
<?php if (luwrain_current_lang() == 'en') {?>
EOF
if [ -r "$ENPAGE" ]; then
    if [ "$FILE_TYPE" == licrict ]; then
	lopsus-page -i "$INDENT" "$ENPAGE"
    elif [ "$FILE_TYPE" == md ]; then
	Markdown.pl < "$ENPAGE"
    else
	echo "$THIS:unknown file type:$FILE_TYPE" >&2 
	exit 1
    fi
fi
cat <<EOF
<?php }?>
<?php if (luwrain_current_lang() == 'ru') {?>
EOF
if [ -r "$RUPAGE" ]; then
    if [ "$FILE_TYPE" == licrict ]; then
	lopsus-page -i "$INDENT" "$RUPAGE"
    elif [ "$FILE_TYPE" == md ]; then
	Markdown.pl < "$RUPAGE"
    else
	echo "$THIS:unknown file type:$FILE_TYPE" >&2 
	exit 1
    fi
fi
cat <<EOF
<?php }?>
<?php luwrain_end_page('/$TARGET');?>
EOF
) > "$OUTPUTFILE"

echo "$OUTPUTFILE"
