#!/bin/sh -e

SRC_DIR=../files
DEST_DIR=lwrcontent:/www/lwr/

find "$SRC_DIR" -type d -exec chmod 755 '{}' \;
find "$SRC_DIR" -type f -exec chmod 644 '{}' \;
chmod 750 "$SRC_DIR"

rsync -vaP --delete "$SRC_DIR/" "$DEST_DIR"

chmod 755 "$SRC_DIR"
